# Generated by Django 4.1 on 2022-09-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoomTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("address", models.CharField(max_length=140)),
                ("price", models.IntegerField(help_text="USD per night")),
                ("beds", models.IntegerField(default=1)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=10)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=10)),
                ("bedrooms", models.IntegerField(default=1)),
                ("bathrooms", models.IntegerField(default=1)),
                ("instant_book", models.BooleanField(default=False)),
                (
                    "room_tag",
                    models.ManyToManyField(
                        null=True, related_name="room_tag", to="rooms.roomtag"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
